name: gregor

services:
  gregor:
    image: node:24-bookworm
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
      - gregor_node_modules:/app/node_modules
    command: sh -c "npm install && npm run build && npm run start"
    restart: unless-stopped

volumes:
  gregor_node_modules:
